name: Student Hub QA Tests
on:
  workflow_dispatch
  # push:
  #   branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]
defaults:
  run:
    working-directory: tests/student-hub
jobs:
  test-win:
    name: "Windows"
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium] # [chromium, firefox, webkit]
    timeout-minutes: 120
    runs-on: windows-latest # macos-latest, ubuntu-latest
    # if: github.event.deployment_status.state == 'success'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: playwright-report
        path: playwright-report