name: Student Hub TEST ONLY
on:
  workflow_dispatch
  # push:
  #   branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]
defaults:
  run:
    working-directory: tests/student-hub
jobs:
  test-win:
    name: "Windows Chromium"
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium] # [chromium, firefox, webkit]
    timeout-minutes: 60
    runs-on: windows-latest # macos-latest, ubuntu-latest
    # if: github.event.deployment_status.state == 'success'
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: |
        npm ci
        npx playwright install-deps
        npx playwright install
    - name: Run Playwright tests
      run: |
        npx playwright test --config playwright.config.js
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report
        retention-days: 30